### PR TITLE
plotting of triangles, edges, and vertices made configurable

### PR DESCRIPTION
**Pull request by tsieger**
`plot.ashape3d.R` accepts flags suppressing plotting of individual graphical elements (triangles, edges, and vertices)

### CODE REVIEW

**Comment by tsieger** [comment]
Oops, sorry, committing too many files.

**Comment by tsieger** [comment]
I accidentally closed this valid PR. Reopening.

**Comment by tsieger** [comment]
Why closing without merging? If you don't like the proposed PR, could you please comment on it?

**Comment by tlafarge** [comment]
Your changes were included in the new version that another collaborator sent me. Being still a beginner in git and github I found it easier to push the new files and close the push request than to handle a then useless merge.

**Pull request closed without merging**
